FROM node:lts

# Set the working directory
WORKDIR /home/microservices/collaboration

# Copy the shared and microservices directories
COPY shared ../../shared
COPY microservices/collaboration ./

# Install dependencies for the shared directory
RUN cd ../../shared && npm install && cd ../microservices/collaboration
# Install dependencies for the microservice
RUN npm install

# Start your application
CMD [ "npm", "run", "start"]
