apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching
  template:
    metadata:
      labels:
        app: matching
    spec:
      containers:
      - name: matching
        image: asia-southeast1-docker.pkg.dev/cs3219-402414/peerprepimages/matching:latest
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
        envFrom:
        - configMapRef:
            name: global-config
        - configMapRef:
            name: matching-config
        resources:
          requests: 
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"