version: "3.8"

x-common-variables: &common-variables
  POSTGRES: postgresql://postgres:postgres@postgres:5432/postgres?connect_timeout=300
  POSTGRES_COLLAB: postgresql://postgres:postgres@postgres-collab:5432/postgres?connect_timeout=300
  MONGO: mongodb://user:password@mongo:27017
  EXE_ENV: DEV
  JWT_SECRET: EXAMPLE_SECRERT # pass around JWT secret so each service can verify user TODO: add to github secrets on deployment
  REFRESH_COOKIE_KEY: EXAMPLE_PEERPREPREFRESHTOKEN
  ACCESS_COOKIE_KEY: EXAMPLE_PEERPREPACCESSTOKEN
  SERVER_PORT: 3000  

networks:
  frontend:
  backend:

services:
  user:
    container_name: user
    build:
      dockerfile: ./microservices/user/Dockerfile.local
      context: ./backend
    volumes:
      - ./backend/microservices/user:/home/microservices/user/
      - /home/microservices/user/node_modules
    ports:
      - 8080:3000
    restart: on-failure
    networks:
      - backend
    environment:
      <<: *common-variables

  question:
    container_name: question
    build:
      dockerfile: ./microservices/question/Dockerfile.local
      context: ./backend
    volumes:
      - ./backend/microservices/question:/home/microservices/question/
      - /home/microservices/question/node_modules
    ports:
      - 3001:3000
    restart: on-failure
    networks:
      - backend
    environment:
      <<: *common-variables

  postgres:
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - "5050:80"
    networks:
      - backend

  mongo:
    container_name: mongo
    build:
      context: ./mongo
      dockerfile: Dockerfile
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - mongo:/data/db
    ports:
      - 27017:27017
    networks:
      - backend

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL="mongo://user:password@mongo:27017/"
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    networks:
      - backend

  nginx:
    depends_on:
      - client
      - user
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3000:80"
    networks:
      - backend
      - frontend

  client:
    build:
      dockerfile: Dockerfile.local
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - frontend
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/key.json

volumes:
  postgres:
  mongo:
