FROM node:lts

# Set the working directory
WORKDIR /home/microservices/question

# Copy the shared and microservices directories
COPY shared ../../shared
COPY microservices/question ./

# Install dependencies for the shared directory
RUN cd ../../shared && npm install && cd ../microservices/question
# Install dependencies for the microservice
RUN npm install

# Start your application
CMD [ "npm", "run", "start"]
