export const MATCHING_REQUEST_VALID_DURATION_IN_SECONDS: number = 30;
export const MATCHING_REQUEST_TOPIC_SUBSCRIPTION: string = "MATCHING_REQUEST_TOPIC-sub";
export const MATCHING_REQUEST_TOPIC_PUBLISH: string = "MATCHING_REQUEST_TOPIC";