FROM node:lts

# Set the working directory
WORKDIR /home/microservices/history

# Copy the shared and microservices directories
COPY shared ../../shared
COPY microservices/history ./

# Install dependencies for the shared directory
RUN cd ../../shared && npm ci && cd ../microservices/history
# Install dependencies for the microservice
RUN npm ci

# Start your application
CMD [ "npm", "run", "dev"]
